name: Deploy to GitHub Pages

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare, build and deploy
        uses: iktnb/github-utils/.github/actions/prepare-and-build-for-gh-pages@v1
        with:
          node-version: "20"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          site_url: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
          output_path: "dist"
          deploy-command: "npm run deploy"
